### ISSUE TITLE
Amazon 

### ISSUE THREAD

**Issue by ClwnMan76** [tasomaniac/OpenLinkWith#23]
Can you PLEASE figure out a way to make Amazon links open in the app??

**Comment by tasomaniac** [comment]
Amazon kinda support some of their links but not all of them. It's a mess. If they do it properly OLW should works itself. 
I have some fixes related to Amazon. The product links should work. 
Can you share some example links that do not work?

**Comment by ClwnMan76** [comment]
WOW! That's incredible response time.  LOL Anyway, yeah, I subscribe to a deal site called uberzonclub.com. You follow a link from your email to their site where they give you a coupon code and a link to go to amazon to purchase it.  I'd be more than happy to forward you an email of you want.

**Comment by tasomaniac** [comment]
Can you send me an email from the app or play store listing? My email is
there.

**Comment by ClwnMan76** [comment]
I sent the link to you.  If you can check it ASAP that'd be great as the coupons go fast.  If that didn't work lemme know.

**Comment by TPS** [comment]
@tasomaniac Sorry to necropost, but Amazon links are broken badly in browser if handled by OLW.  Is it perhaps d/t whatever link mangling you did (above) to get them to work for Amazon app?  I thought originally it was because of another app, so posted details originally @ https://github.com/svenjacobs/leon/issues/168#issuecomment-2451288245
