### ISSUE TITLE
Latest version (1.5) from Play Store crashing on startup

### ISSUE THREAD

**Issue by Yowlen** [tasomaniac/OpenLinkWith#32]
I can't use this version at all, whether I'm opening the main screen or via intents. I'm running a custom 5.1.1 ROM on an LG Leon (H345/MS345). I sent a report via Google's report system titled "Crashes on startup" (without the quotes) so I hope you can get this fixed soon.

**Comment by tasomaniac** [comment]
Thanks for the issue. For some reason this is not visible on Fabric. I guess it is because it is a crash on the app start. :(
I saw the crash on Google Play Console.
It is not happening for me so I cannot test the fix. Can you check the latest beta version? I published it. Will probably be available in the next hour.

**Comment by Yowlen** [comment]
It works now. Thanks. :)

**Comment by tasomaniac** [comment]
It was a Dagger related problem. It may not be something they fix but it is still interesting. Will open a report on Google Dagger repo. Thanks again for the report.
